### ISSUE TITLE
Deprecate Binary, Hexadecimal and Octal

### ISSUE THREAD

**Issue by kukimik** [exercism/roc#137]
Hi! Thanks for your work on the Roc track.

I've noticed some problems with the specification of the "Binary" exercise and wrote about them in the forums:

* https://forum.exercism.org/t/binary-should-empty-input-be-rejected/13282
* https://forum.exercism.org/t/binary-expected-output-is-not-decimal-representation-of-a-number/13281

It turned out that the exercise [has been deprecated for 7 years](https://github.com/exercism/problem-specifications/blob/main/exercises/binary/.deprecated) and "All of your base" should be implemented instead. As the Roc track already has the  "All of your base" exercise, I think the "Binary" exercise can be removed from the track.

The same applies to ["Hexadecimal"](https://github.com/exercism/problem-specifications/blob/main/exercises/hexadecimal/.deprecated) and ["Octal"](https://github.com/exercism/problem-specifications/blob/main/exercises/octal/.deprecated).

----

EDIT: "Accumulate" is also [deprecated](https://github.com/exercism/problem-specifications/blob/main/exercises/accumulate/.deprecated), list-ops should be implemented instead.

**Comment by ageron** [comment]
Oh I didn't notice these deprecations, thanks for letting me know. I'll remove them.
