### ISSUE TITLE
Clock - extreme values test cases?

### ISSUE THREAD

**Issue by kukimik** [exercism/roc#150]
What do you think about adding tests that check the program works correctly for extreme values of `hours` and `minutes`, i.e.: -9_223_372_036_854_775_808 and 9_223_372_036_854_775_807?

On the one hand, it is simple and elegant to define `subtract` in terms of `add` by setting:

```roc
subtract = \clock, {hours, minutes} -> add clock {hours : -hours, minutes : -minutes}
```

and in practice this is often the "right" thing to do. This approach teaches code reuse.

On the other hand, `subtract` defined as above will fail if either `hours` or `minutes` have value `-9_223_372_036_854_775_808`. If this case is included in the tests, it can teach being careful about overflows.

-----------

Also, for such inputs some reasonable programs will fail at converting hours to minutes and other similar operations.

**Comment by ageron** [comment]
Great idea! Would you like to submit a PR or would you prefer I do it (I'm fine either way)? Adding extra tests requires adding a `.meta/additional_tests.json` file, then you can iterate over these test cases at the end of `template.j2` using `{% for case in additional_cases %}...{% endfor %}`, see #149 for an example. Then you can generate the new test file by running `bin/generate_tests.py clock`. You may need to install Python and the libraries listed in `requirements-generator.txt` (using `python -m pip install -r requirements-generator.txt`).

**Comment by kukimik** [comment]
Thanks for your kind words! And I really appreciate the instructions you gave, I think it's a very good approach towards new contributors. Unfortunately I've been feeling somewhat overloaded recently, and I'd rather not add this to my TODO list. So if you are fine with creating a PR, that would be great.

**Comment by ageron** [comment]
Hi @kukimik ,
I've submitted PR #155 if you want to take a look? It complicates the solution quite a bit, so I'm thinking it might be better to test that the program either returns `Ok` with the correct answer, or an `Err`, but never crashes. This way the users learn to be careful about overflows, but they can choose to fully support extreme values, or to return an `Err` when the input is larger than some threshold (if they're a bit lazy). Wdyt?

**Comment by kukimik** [comment]
@ageron  Thanks, I'll take a look at it in a few days.

**Comment by kukimik** [comment]
Looks like I'm late. Sorry. Anyway, thanks for handling this!

**Comment by ageron** [comment]
No worries at all, thanks for the suggestion!
