### ISSUE TITLE
Anagram: add another non-ascii test

### ISSUE THREAD

**Issue by chuckwondo** [exercism/roc#170]
I suggest adding 1 more test case to Anagram:

```roc
# non-ascii characters should work
expect
    result = findAnagrams "A€" ["€a"]
    result == ["€a"]
```

Justification: it is possible to "accidentally" pass the existing non-ascii test by "ignoring" all non-ascii bytes (obtained from simply converting strings to utf8 bytes), as in this solution: https://exercism.org/tracks/roc/exercises/anagram/solutions/Bahm.

That solution passes all existing tests, but fails the additional test given above because the solution simply ignores (throws out) all non-ascii characters, thus it effectively treats the above test as though the subject is "A" and the candidate is "a", thus erroneously yielding an empty result (due to considering the subject and candidate as being equal, ignoring case -- i.e. "A" equals "a", ignoring case).

**Comment by chuckwondo** [comment]
I just realized that this is perhaps not Roc-specific, but rather applies to the Anagram exercise as a whole. If that's the case, where should I submit this issue instead of here?

**Comment by Anton-4** [comment]
I think this may be a deliberate choice, you can ask on the [exercism forum](https://forum.exercism.org/). Feel free to re-open this issue if people there approve of the addition of this test.
