### ISSUE TITLE
Interrupting bin/verify-exercises leaves the files in a modified state

### ISSUE THREAD

**Issue by ageron** [exercism/roc#30]
For example, if you type Ctrl-C while the test for the `collatz-conjecture` exercise is running and run `git status`, you'll see:

```bash
 M exercises/practice/collatz-conjecture/CollatzConjecture.roc
?? exercises/practice/collatz-conjecture/CollatzConjecture.roc.bak
```

It would be cleaner to run the tests in the `/tmp` directory.

**Comment by ErikSchierboom** [comment]
The latest version of the script in the generic-track repo does this:

https://github.com/exercism/generic-track/blob/main/bin/verify-exercises#L55-L75
